#!/usr/bin/env node
/**
 * iMach — Prototype Icon Extractor
 * ------------------------------------------------------------
 * Extracts every <symbol> from redesign-final/index.html (the v18
 * Reference Prototype SVG sprite: 44 `i-*` UI icons + 4 `a-*` goods
 * art icons + marks) and generates:
 *
 *   components/imach/icon-sprite.tsx — the sprite body (verbatim) +
 *                                      <IconSprite/> mount component
 *   components/imach/icon.tsx       — typed <Icon name="i-bell" …/>
 *                                      using <use href="#i-bell">
 *
 * Prototype fidelity rule (§50): these icons are THE product icons —
 * they are never swapped for Lucide or any other set. Re-run after
 * prototype icon changes:
 *   node scripts/extract-icons.mjs
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const SRC = path.resolve("redesign-final/index.html");
const OUT_DIR = path.resolve("components/imach");

const html = await readFile(SRC, "utf8");

// capture every <symbol …>…</symbol> block (ids like i-bell / a-rice / i-bm)
const symbols = [];
const re = /<symbol\s+([^>]*)>([\s\S]*?)<\/symbol>/g;
for (const m of html.matchAll(re)) {
  const attrs = m[1];
  const id = /id="([a-z0-9-]+)"/.exec(attrs)?.[1];
  if (!id) continue;
  symbols.push({ id, attrs: attrs.replace(/id="[a-z0-9-]+"?\s*/g, "").trim(), body: m[2].trim() });
}

if (symbols.length === 0) {
  console.error("✖ no <symbol> found — is redesign-final/index.html in place?");
  process.exit(1);
}

// ── icon-sprite.tsx ──────────────────────────────────────────────────
const spriteBody = symbols
  .map((s) => `  <symbol id="${s.id}" ${s.attrs}>${s.body}</symbol>`)
  .join("\n");

/** SVG attribute names → React camelCase (avoids invalid-DOM-property warnings) */
const SVG_ATTR_CAMEL = {
  "stroke-width": "strokeWidth",
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "stroke-dasharray": "strokeDasharray",
  "stroke-dashoffset": "strokeDashoffset",
  "stroke-opacity": "strokeOpacity",
  "fill-rule": "fillRule",
  "clip-rule": "clipRule",
  "fill-opacity": "fillOpacity",
  "stop-color": "stopColor",
  "stop-opacity": "stopOpacity",
};

/** parse symbol attributes (viewBox/fill/stroke/…) into a React-safe object */
function parseAttrs(raw) {
  const attrs = {};
  for (const m of raw.matchAll(/([a-zA-Z:-]+)="([^"]*)"/g)) {
    const key = SVG_ATTR_CAMEL[m[1]] ?? m[1];
    attrs[key] = m[2];
  }
  return attrs;
}

const spriteTsx = `/* (unused draft) */\n`;

const spriteTsxFinal = `/* GENERATED by scripts/extract-icons.mjs from redesign-final/index.html — do not hand-edit.
   The complete v18 prototype icon set (i-* UI icons + a-* goods art + marks),
   verbatim. Mounted once by the (app) shell layout; <Icon> references each
   symbol by id via SVG <use>. */

interface SymbolDef { id: string; attrs: Record<string, string>; body: string; }

export const ICON_SYMBOLS: SymbolDef[] = [
${symbols.map((s) => `  { id: ${JSON.stringify(s.id)}, attrs: ${JSON.stringify(parseAttrs(s.attrs))}, body: ${JSON.stringify(s.body)} },`).join("\n")}
];

/** The hidden SVG sprite — mount ONCE at the app shell root. */
export function IconSprite() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" style={{ display: "none" }} aria-hidden="true" focusable="false">
      {ICON_SYMBOLS.map((s) => (
        <symbol key={s.id} id={s.id} {...s.attrs} dangerouslySetInnerHTML={{ __html: s.body }} />
      ))}
    </svg>
  );
}
`;

// ── icon.tsx ─────────────────────────────────────────────────────────
const iconTsx = `/* GENERATED by scripts/extract-icons.mjs — do not hand-edit.
   Typed icon reference: <Icon name="i-bell" className="ic" /> renders
   the exact prototype markup <svg class="ic"><use href="#i-bell"/></svg>.
   Sizing comes from the prototype CSS (svg.ic / .ic-sm / .ic-lg …). */

import type { CSSProperties } from "react";

export const ICON_NAMES = [
${symbols.map((s) => `  "${s.id}",`).join("\n")}
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export function Icon({
  name,
  className,
  style,
}: {
  name: IconName;
  className?: string;
  style?: CSSProperties;
}) {
  return (
    <svg className={className} style={style} aria-hidden="true" focusable="false">
      <use href={\`#\${name}\`} />
    </svg>
  );
}
`;

await mkdir(OUT_DIR, { recursive: true });
await writeFile(path.join(OUT_DIR, "icon-sprite.tsx"), spriteTsxFinal);
await writeFile(path.join(OUT_DIR, "icon.tsx"), iconTsx);

console.log(`▣ extracted ${symbols.length} symbols → components/imach/icon-sprite.tsx + icon.tsx`);
console.log(`  ids: ${symbols.map((s) => s.id).join(", ")}`);
