/* GENERATED by scripts/extract-icons.mjs — do not hand-edit.
   Typed icon reference: <Icon name="i-bell" className="ic" /> renders
   the exact prototype markup <svg class="ic"><use href="#i-bell"/></svg>.
   Sizing comes from the prototype CSS (svg.ic / .ic-sm / .ic-lg …). */

import type { CSSProperties } from "react";

export const ICON_NAMES = [
  "i-basket",
  "i-box",
  "i-store",
  "i-list",
  "i-users",
  "i-spark",
  "i-user",
  "i-bell",
  "i-search",
  "i-plus",
  "i-back",
  "i-chev",
  "i-arrf",
  "i-share",
  "i-bm",
  "i-bmf",
  "i-eye",
  "i-pin",
  "i-clock",
  "i-check",
  "i-checkc",
  "i-info",
  "i-star",
  "i-edit",
  "i-chart",
  "i-inbox",
  "i-x",
  "i-tel",
  "i-tdn",
  "i-tup",
  "i-truck",
  "i-shield",
  "i-img",
  "i-gear",
  "i-out",
  "i-globe",
  "i-send",
  "i-msg",
  "i-sort",
  "i-trash",
  "i-bolt",
  "i-wallet",
  "i-percent",
  "i-steps",
  "i-tag",
  "a-rice",
  "a-oil",
  "a-sugar",
  "a-lentil",
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export function Icon({
  name,
  className,
  style,
}: {
  name: IconName;
  className?: string;
  style?: CSSProperties;
}) {
  return (
    <svg className={className} style={style} aria-hidden="true" focusable="false">
      <use href={`#${name}`} />
    </svg>
  );
}
